# Generated by Django 4.0.7 on 2023-03-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('noofwords', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdno', models.IntegerField()),
                ('tag', models.CharField(max_length=1)),
                ('word', models.CharField(max_length=60)),
                ('ans', models.CharField(max_length=200)),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sentence')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.verifier')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.confirmer')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.annotator')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sentence')),
            ],
        ),
    ]
