# Generated by Django 4.0.7 on 2023-04-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
