# Generated by Django 4.0.7 on 2023-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sentence_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='lock',
            field=models.IntegerField(default=0),
        ),
    ]
