# Generated by Django 4.0.7 on 2023-04-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sentence_meaning_alter_sentence_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='meaning',
            field=models.CharField(blank=True, max_length=99999),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='tags',
            field=models.CharField(max_length=999999),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='words',
            field=models.CharField(max_length=999999),
        ),
    ]
