# Generated by Django 4.0.7 on 2023-03-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('aid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('score', models.BigIntegerField()),
                ('logged_in', models.BooleanField(default=False)),
                ('password', models.TextField(max_length=200)),
                ('mobileno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmer',
            fields=[
                ('vid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('logged_in', models.BooleanField(default=False)),
                ('password', models.TextField(max_length=200)),
                ('mobileno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('vid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('score', models.BigIntegerField()),
                ('username', models.CharField(max_length=60)),
                ('logged_in', models.BooleanField(default=False)),
                ('password', models.TextField(max_length=200)),
                ('mobileno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
    ]
