# Generated by Django 3.2.6 on 2023-03-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('aid', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(blank=True, max_length=60)),
                ('score', models.BigIntegerField(default=0)),
                ('password', models.TextField(max_length=200)),
                ('mobileno', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=70)),
                ('tag', models.IntegerField(default=0)),
            ],
        ),
    ]
