# Generated by Django 4.0.7 on 2023-04-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lowerb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='upperb',
            field=models.IntegerField(default=0),
        ),
    ]
