# Generated by Django 3.2.6 on 2023-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AddField(
            model_name='users',
            name='password1',
            field=models.TextField(default='password', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='password2',
            field=models.TextField(default='password', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
