# Generated by Django 3.2.6 on 2023-03-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230321_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='aid',
        ),
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
